/**
 * Extension Runtime Configuration
 *
 * Generated by scripts/generate-extension-config.mjs
 * Do not edit manually.
 */
(function () {
  const root = typeof window !== 'undefined' ? window : self;
  if (root.LOCKIN_CONFIG) {
    return;
  }

  const APP_ENV = 'local';
  const IS_PRODUCTION = APP_ENV === 'production';

  root.LOCKIN_CONFIG = {
    APP_ENV,
    IS_PRODUCTION,
    BACKEND_URL: 'http://localhost:3000',
    SUPABASE_URL: 'http://localhost:54321',
    SUPABASE_ANON_KEY: '',
    SUPABASE_ENVIRONMENT: 'local',
    SESSION_STORAGE_KEY: 'lockinSupabaseSession',
    TOKEN_EXPIRY_BUFFER_MS: 60000,
    DEBUG_PANOPTO_RESOLVER: !IS_PRODUCTION,
  };

  if (!IS_PRODUCTION && typeof console !== 'undefined') {
    console.log('[Lock-in] Extension config loaded:', {
      environment: APP_ENV,
      supabase: root.LOCKIN_CONFIG.SUPABASE_ENVIRONMENT,
      backendUrl: root.LOCKIN_CONFIG.BACKEND_URL,
    });
  }
})();
