const path = require('path');
const { readNumber } = require('./utils');
const { OPENAI_TRANSCRIPTION_MODEL } = require('./llm');
const {
  EIGHT,
  FIVE,
  FOUR,
  SEVEN,
  SIX,
  TEN,
  THIRTY,
  SIXTY,
  THREE,
  TWO,
} = require('../constants/numbers');
const { KIBIBYTE, MEBIBYTE } = require('./units');

const DEFAULT_SEGMENT_MAX_MB = FOUR * SIX;
const HALF_KIBIBYTE = KIBIBYTE / TWO;
const DEFAULT_TOTAL_BYTES = HALF_KIBIBYTE * MEBIBYTE;
const DEFAULT_RETENTION_HOURS = SIX * EIGHT;

// Transcript processing
const TRANSCRIPTION_MODEL = OPENAI_TRANSCRIPTION_MODEL;
const TRANSCRIPTION_SEGMENT_MAX_MB = readNumber(
  process.env.TRANSCRIPTION_SEGMENT_MAX_MB,
  DEFAULT_SEGMENT_MAX_MB,
);
const TRANSCRIPTION_TEMP_DIR =
  process.env.TRANSCRIPTION_TEMP_DIR || path.join(__dirname, '..', 'tmp', 'transcripts');
const TRANSCRIPT_CHUNK_MAX_BYTES = readNumber(
  process.env.TRANSCRIPT_CHUNK_MAX_BYTES,
  EIGHT * MEBIBYTE,
);
const TRANSCRIPT_DAILY_JOB_LIMIT = readNumber(process.env.TRANSCRIPT_DAILY_JOB_LIMIT, TEN * TWO);
const TRANSCRIPT_MAX_CONCURRENT_JOBS = readNumber(
  process.env.TRANSCRIPT_MAX_CONCURRENT_JOBS,
  THREE,
);
const TRANSCRIPT_MAX_TOTAL_BYTES = readNumber(
  process.env.TRANSCRIPT_MAX_TOTAL_BYTES,
  DEFAULT_TOTAL_BYTES,
);
const TRANSCRIPT_MAX_DURATION_MINUTES = readNumber(
  process.env.TRANSCRIPT_MAX_DURATION_MINUTES,
  THREE * SIXTY,
);
const TRANSCRIPT_JOBS_BUCKET = process.env.TRANSCRIPT_JOBS_BUCKET || 'transcript-jobs';
// Rate limit for chunk uploads: 512MB/minute allows reasonable upload speed
// while still providing abuse protection (enforced per-user per-minute window)
const TRANSCRIPT_UPLOAD_BYTES_PER_MINUTE = readNumber(
  process.env.TRANSCRIPT_UPLOAD_BYTES_PER_MINUTE,
  DEFAULT_TOTAL_BYTES,
);
const TRANSCRIPT_JOB_TTL_MINUTES = readNumber(process.env.TRANSCRIPT_JOB_TTL_MINUTES, SIXTY);
const TRANSCRIPT_JOB_REAPER_INTERVAL_MINUTES = readNumber(
  process.env.TRANSCRIPT_JOB_REAPER_INTERVAL_MINUTES,
  TEN,
);
const TRANSCRIPT_CHUNK_RETENTION_HOURS = readNumber(
  process.env.TRANSCRIPT_CHUNK_RETENTION_HOURS,
  DEFAULT_RETENTION_HOURS,
);
const TRANSCRIPT_CHUNK_HARD_TTL_DAYS = readNumber(
  process.env.TRANSCRIPT_CHUNK_HARD_TTL_DAYS,
  SEVEN,
);
const TRANSCRIPT_PROCESSING_HEARTBEAT_INTERVAL_SECONDS = readNumber(
  process.env.TRANSCRIPT_PROCESSING_HEARTBEAT_INTERVAL_SECONDS,
  THIRTY,
);
const TRANSCRIPT_PROCESSING_STALE_MINUTES = readNumber(
  process.env.TRANSCRIPT_PROCESSING_STALE_MINUTES,
  FIVE,
);

module.exports = {
  TRANSCRIPTION_MODEL,
  TRANSCRIPTION_SEGMENT_MAX_MB,
  TRANSCRIPTION_TEMP_DIR,
  TRANSCRIPT_CHUNK_MAX_BYTES,
  TRANSCRIPT_DAILY_JOB_LIMIT,
  TRANSCRIPT_MAX_CONCURRENT_JOBS,
  TRANSCRIPT_MAX_TOTAL_BYTES,
  TRANSCRIPT_MAX_DURATION_MINUTES,
  TRANSCRIPT_JOBS_BUCKET,
  TRANSCRIPT_UPLOAD_BYTES_PER_MINUTE,
  TRANSCRIPT_JOB_TTL_MINUTES,
  TRANSCRIPT_JOB_REAPER_INTERVAL_MINUTES,
  TRANSCRIPT_CHUNK_RETENTION_HOURS,
  TRANSCRIPT_CHUNK_HARD_TTL_DAYS,
  TRANSCRIPT_PROCESSING_HEARTBEAT_INTERVAL_SECONDS,
  TRANSCRIPT_PROCESSING_STALE_MINUTES,
};
