/**
 * HTTP Request Logging Middleware with Correlation IDs
 *
 * Provides:
 * - Unique request ID for every request (X-Request-ID header)
 * - Structured request/response logging
 * - Correlation ID propagation to Sentry
 * - Integration with pino-http
 */

const pinoHttp = require('pino-http');
const { v4: uuidv4 } = require('uuid');
const Sentry = require('@sentry/node');
const { logger } = require('./index');

const IS_PRODUCTION = process.env.NODE_ENV === 'production';

/**
 * Generate a unique request ID.
 * Uses client-provided X-Request-ID if present, otherwise generates a new UUID.
 *
 * @param {Object} req - Express request object
 * @returns {string} Request ID
 */
function generateRequestId(req) {
  return req.headers['x-request-id'] || uuidv4();
}

/**
 * Create the pino-http middleware for structured request logging.
 *
 * Features:
 * - Assigns unique request ID to every request
 * - Logs request start and completion
 * - Includes response time and status
 * - Sanitizes sensitive headers
 *
 * @returns {Function} Express middleware
 */
function createRequestLogger() {
  return pinoHttp({
    logger,

    // Generate/preserve request ID
    genReqId: generateRequestId,

    // Custom serializers for privacy
    serializers: {
      req: (req) => ({
        id: req.id,
        method: req.method,
        url: req.url,
        // Omit sensitive headers
        headers: sanitizeHeaders(req.headers),
      }),
      res: (res) => ({
        statusCode: res.statusCode,
      }),
      // Don't log error details in request logs (Sentry handles errors)
      err: () => undefined,
    },

    // Custom log level based on status code
    customLogLevel: (req, res, error) => {
      if (error || res.statusCode >= 500) return 'error';
      if (res.statusCode >= 400) return 'warn';
      return 'info';
    },

    // Only log health checks at debug level (reduce noise)
    autoLogging: {
      ignore: (req) => {
        // Skip health check logging in production to reduce noise
        if (IS_PRODUCTION && req.url === '/health') {
          return true;
        }
        return false;
      },
    },

    // Custom success message
    customSuccessMessage: (req, res) => {
      return `${req.method} ${req.url} ${res.statusCode}`;
    },

    // Custom error message
    customErrorMessage: (req, res) => {
      return `${req.method} ${req.url} ${res.statusCode} - Error`;
    },

    // Add custom attributes to log context
    customAttributeKeys: {
      req: 'request',
      res: 'response',
      err: 'error',
      responseTime: 'latencyMs',
    },
  });
}

/**
 * Remove sensitive headers from log output.
 *
 * @param {Object} headers - Request headers
 * @returns {Object} Sanitized headers
 */
function sanitizeHeaders(headers) {
  if (!headers) return {};

  const sanitized = { ...headers };

  // Remove sensitive headers
  const sensitiveHeaders = [
    'authorization',
    'cookie',
    'x-api-key',
    'x-auth-token',
    'x-supabase-auth',
  ];

  for (const header of sensitiveHeaders) {
    if (sanitized[header]) {
      sanitized[header] = '[REDACTED]';
    }
  }

  return sanitized;
}

/**
 * Middleware to propagate request ID to Sentry for error correlation.
 *
 * @param {Object} req - Express request object
 * @param {Object} res - Express response object
 * @param {Function} next - Next middleware
 */
function sentryRequestIdMiddleware(req, res, next) {
  // Get request ID from pino-http (already generated by createRequestLogger)
  const requestId = req.id || req.headers['x-request-id'] || uuidv4();

  // Store on request for downstream use
  req.requestId = requestId;

  // Add to response headers for client correlation
  res.setHeader('X-Request-ID', requestId);

  // Set Sentry context with request ID
  Sentry.setTag('request_id', requestId);
  Sentry.setContext('request', {
    id: requestId,
    method: req.method,
    url: req.url,
  });

  next();
}

/**
 * Create a child logger bound to the current request context.
 * Use this in route handlers for request-scoped logging.
 *
 * @param {Object} req - Express request object
 * @returns {Object} Pino child logger
 */
function getRequestLogger(req) {
  // pino-http attaches logger to req.log
  return req.log || logger;
}

module.exports = {
  createRequestLogger,
  sentryRequestIdMiddleware,
  getRequestLogger,
  generateRequestId,
  sanitizeHeaders,
};
