const MAX_HISTORY_MESSAGES = 30;
const MAX_ATTACHMENT_CONTEXT_CHARS = 5000;
const MIN_SELECTION_PRIMARY_CHARS = 20;
const ATTACHMENT_ONLY_SELECTION_PLACEHOLDER = '[Document-based question - see attached files]';

module.exports = {
  MAX_HISTORY_MESSAGES,
  MAX_ATTACHMENT_CONTEXT_CHARS,
  MIN_SELECTION_PRIMARY_CHARS,
  ATTACHMENT_ONLY_SELECTION_PLACEHOLDER,
};
