export const API_CLIENT_EXPECTED_KEYS = [
  "apiRequest",
  "chatWithNotes",
  "createNote",
  "deleteChat",
  "deleteNote",
  "deleteNoteAsset",
  "generateChatTitle",
  "getBackendUrl",
  "getChatMessages",
  "getRecentChats",
  "listNoteAssets",
  "listNotes",
  "processText",
  "searchNotes",
  "setNoteStar",
  "toggleNoteStar",
  "updateNote",
  "uploadNoteAsset",
] as const;

