export const API_CLIENT_EXPECTED_KEYS = [
  'apiRequest',
  'cacheTranscript',
  'chatWithNotes',
  'createChat',
  'createNote',
  'deleteChat',
  'deleteChatAsset',
  'deleteNote',
  'deleteNoteAsset',
  'generateChatTitle',
  'getBackendUrl',
  'getChatMessages',
  'getFeedback',
  'getRecentChats',
  'listChatAssets',
  'listFeedback',
  'listNoteAssets',
  'listNotes',
  'processText',
  'searchNotes',
  'setNoteStar',
  'submitFeedback',
  'toggleNoteStar',
  'updateNote',
  'uploadChatAsset',
  'uploadNoteAsset',
] as const;
