const { ONE, TWO, THREE, FOUR, FIVE, EIGHT, NINE, THIRTY, HUNDRED } = require('./numbers');

const OK = TWO * HUNDRED;
const CREATED = OK + ONE;
const NO_CONTENT = OK + FOUR;

const BAD_REQUEST = FOUR * HUNDRED;
const UNAUTHORIZED = BAD_REQUEST + ONE;
const FORBIDDEN = BAD_REQUEST + THREE;
const NOT_FOUND = BAD_REQUEST + FOUR;
const REQUEST_TIMEOUT = BAD_REQUEST + EIGHT;
const CONFLICT = BAD_REQUEST + NINE;
const TOO_MANY_REQUESTS = BAD_REQUEST + (THIRTY - ONE);

const INTERNAL_SERVER_ERROR = FIVE * HUNDRED;
const BAD_GATEWAY = INTERNAL_SERVER_ERROR + TWO;
const SERVICE_UNAVAILABLE = INTERNAL_SERVER_ERROR + THREE;
const GATEWAY_TIMEOUT = INTERNAL_SERVER_ERROR + FOUR;

module.exports = {
  OK,
  CREATED,
  NO_CONTENT,
  BAD_REQUEST,
  UNAUTHORIZED,
  FORBIDDEN,
  NOT_FOUND,
  REQUEST_TIMEOUT,
  CONFLICT,
  TOO_MANY_REQUESTS,
  INTERNAL_SERVER_ERROR,
  BAD_GATEWAY,
  SERVICE_UNAVAILABLE,
  GATEWAY_TIMEOUT,
};
